/**
 * 
 * 
qd = [0, 20, 30, 40, 50, 60, 70, 80, 90, 100],
mp = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
jl = [0, 20, 30, 40, 50, 60, 70, 80, 90, 100],
sb = [0, 3, 6, 9, 12, 15, 18, 22, 26, 30, 40, 50, 60, 70, 85, 100],
ly = [0, 3, 6, 9, 12, 15, 18, 22, 26, 30, 40, 50, 60, 70, 85, 100],
dy = [0, 5, 8, 12, 16, 20, 24, 28, 32, 35, 40, 50, 60, 70, 85, 100],
sl = [0, 8, 13, 18, 24, 30, 35, 40, 45, 50, 55, 60, 65, 70, 85, 100],
xl = [0, 3, 5, 7, 9, 12, 14, 16, 18, 20, 35, 50, 55, 65, 75, 85, 100],
vl = [0, 8, 12, 16, 20, 24, 28, 32, 36, 40, 50, 60, 70, 80, 90, 100],
rh = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
 */
const mapping = {
    "qd":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":20
            },
            {
                "oriValue":2,
                "map":30
            },
            {
                "oriValue":3,
                "map":40
            },
            {
                "oriValue":4,
                "map":50
            },
            {
                "oriValue":5,
                "map":60
            },
            {
                "oriValue":6,
                "map":70
            },
            {
                "oriValue":7,
                "map":80
            },
            {
                "oriValue":8,
                "map":90
            },
            {
                "oriValue":9,
                "map":100
            }
        ]
    },
    "mp":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":10
            },
            {
                "oriValue":2,
                "map":20
            },
            {
                "oriValue":3,
                "map":30
            },
            {
                "oriValue":4,
                "map":40
            },
            {
                "oriValue":5,
                "map":50
            },
            {
                "oriValue":6,
                "map":60
            },
            {
                "oriValue":7,
                "map":70
            },
            {
                "oriValue":8,
                "map":80
            },
            {
                "oriValue":9,
                "map":90
            },
            {
                "oriValue":10,
                "map":100
            }
        ]
    },
    "jl":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":20
            },
            {
                "oriValue":2,
                "map":30
            },
            {
                "oriValue":3,
                "map":40
            },
            {
                "oriValue":4,
                "map":50
            },
            {
                "oriValue":5,
                "map":60
            },
            {
                "oriValue":6,
                "map":70
            },
            {
                "oriValue":7,
                "map":80
            },
            {
                "oriValue":8,
                "map":90
            },
            {
                "oriValue":9,
                "map":100
            }
        ]
    },
    "sb":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":3
            },
            {
                "oriValue":2,
                "map":6
            },
            {
                "oriValue":3,
                "map":9
            },
            {
                "oriValue":4,
                "map":12
            },
            {
                "oriValue":5,
                "map":15
            },
            {
                "oriValue":6,
                "map":18
            },
            {
                "oriValue":7,
                "map":22
            },
            {
                "oriValue":8,
                "map":26
            },
            {
                "oriValue":9,
                "map":30
            },
            {
                "oriValue":10,
                "map":40
            },
            {
                "oriValue":11,
                "map":50
            },
            {
                "oriValue":12,
                "map":60
            },
            {
                "oriValue":13,
                "map":70
            },
            {
                "oriValue":14,
                "map":85
            },
            {
                "oriValue":15,
                "map":100
            }
        ]
    },
    "ly":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":3
            },
            {
                "oriValue":2,
                "map":6
            },
            {
                "oriValue":3,
                "map":9
            },
            {
                "oriValue":4,
                "map":12
            },
            {
                "oriValue":5,
                "map":15
            },
            {
                "oriValue":6,
                "map":18
            },
            {
                "oriValue":7,
                "map":22
            },
            {
                "oriValue":8,
                "map":26
            },
            {
                "oriValue":9,
                "map":30
            },
            {
                "oriValue":10,
                "map":40
            },
            {
                "oriValue":11,
                "map":50
            },
            {
                "oriValue":12,
                "map":60
            },
            {
                "oriValue":13,
                "map":70
            },
            {
                "oriValue":14,
                "map":85
            },
            {
                "oriValue":15,
                "map":100
            }
        ]
    },
    "dy":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":5
            },
            {
                "oriValue":2,
                "map":8
            },
            {
                "oriValue":3,
                "map":12
            },
            {
                "oriValue":4,
                "map":16
            },
            {
                "oriValue":5,
                "map":20
            },
            {
                "oriValue":6,
                "map":24
            },
            {
                "oriValue":7,
                "map":28
            },
            {
                "oriValue":8,
                "map":32
            },
            {
                "oriValue":9,
                "map":35
            },
            {
                "oriValue":10,
                "map":40
            },
            {
                "oriValue":11,
                "map":50
            },
            {
                "oriValue":12,
                "map":60
            },
            {
                "oriValue":13,
                "map":70
            },
            {
                "oriValue":14,
                "map":85
            },
            {
                "oriValue":15,
                "map":100
            }
        ]
    },
    "sl":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":8
            },
            {
                "oriValue":2,
                "map":13
            },
            {
                "oriValue":3,
                "map":18
            },
            {
                "oriValue":4,
                "map":24
            },
            {
                "oriValue":5,
                "map":30
            },
            {
                "oriValue":6,
                "map":35
            },
            {
                "oriValue":7,
                "map":40
            },
            {
                "oriValue":8,
                "map":45
            },
            {
                "oriValue":9,
                "map":50
            },
            {
                "oriValue":10,
                "map":55
            },
            {
                "oriValue":11,
                "map":60
            },
            {
                "oriValue":12,
                "map":65
            },
            {
                "oriValue":13,
                "map":70
            },
            {
                "oriValue":14,
                "map":85
            },
            {
                "oriValue":15,
                "map":100
            }
        ]
    },
    "xl":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":3
            },
            {
                "oriValue":2,
                "map":5
            },
            {
                "oriValue":3,
                "map":7
            },
            {
                "oriValue":4,
                "map":9
            },
            {
                "oriValue":5,
                "map":12
            },
            {
                "oriValue":6,
                "map":14
            },
            {
                "oriValue":7,
                "map":16
            },
            {
                "oriValue":8,
                "map":18
            },
            {
                "oriValue":9,
                "map":20
            },
            {
                "oriValue":10,
                "map":35
            },
            {
                "oriValue":11,
                "map":50
            },
            {
                "oriValue":12,
                "map":55
            },
            {
                "oriValue":13,
                "map":65
            },
            {
                "oriValue":14,
                "map":75
            },
            {
                "oriValue":15,
                "map":85
            },
            {
                "oriValue":16,
                "map":100
            }
        ]
    },
    "vl":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":8
            },
            {
                "oriValue":2,
                "map":12
            },
            {
                "oriValue":3,
                "map":16
            },
            {
                "oriValue":4,
                "map":20
            },
            {
                "oriValue":5,
                "map":24
            },
            {
                "oriValue":6,
                "map":28
            },
            {
                "oriValue":7,
                "map":32
            },
            {
                "oriValue":8,
                "map":36
            },
            {
                "oriValue":9,
                "map":40
            },
            {
                "oriValue":10,
                "map":50
            },
            {
                "oriValue":11,
                "map":60
            },
            {
                "oriValue":12,
                "map":70
            },
            {
                "oriValue":13,
                "map":80
            },
            {
                "oriValue":14,
                "map":90
            },
            {
                "oriValue":15,
                "map":100
            }
        ]
    },
    "rh":{
        "mapV":[
            {
                "oriValue":0,
                "map":0
            },
            {
                "oriValue":1,
                "map":10
            },
            {
                "oriValue":2,
                "map":20
            },
            {
                "oriValue":3,
                "map":30
            },
            {
                "oriValue":4,
                "map":40
            },
            {
                "oriValue":5,
                "map":50
            },
            {
                "oriValue":6,
                "map":60
            },
            {
                "oriValue":7,
                "map":70
            },
            {
                "oriValue":8,
                "map":80
            },
            {
                "oriValue":9,
                "map":90
            },
            {
                "oriValue":10,
                "map":100
            }
        ]
    }
}
export default mapping;
