const treeRule = {
    "tree":{
        "SkinImprove":{
            "show":true,
            "chinese":"皮肤改善工作流",
            "child":{
                "dynamicSkinSmooth":{
                    "show":false,
                    "chinese":"动态皮肤光滑"
                },
                "useFaceMask":{
                    "show":false,
                    "chinese":"使用皮肤蒙版"
                }
            }
        },
        "HighPass":{
            "show":true,
            "chinese":"高反差保留",
            "child":{
                "useFaceMask":{
                    "show":false,
                    "chinese":"使用皮肤蒙版"
                }
            }
        },
        "Lut":{
            "show":false,
            "chinese":"lut处理",
            "child":{
                "useFaceMask":{
                    "show":false,
                    "chinese":"使用皮肤蒙版"
                }
            }
        },
        "Makeup":{
            "show":true,
            "chinese":"美妆",
            "child":{
                "men":{
                    "show":true,
                    "chinese":"男",
                    "child":{
                        "conditionalJudgment":{
                            "show":true,
                            "chinese":"附条件判决"
                        },
                        "conditionalJudgmentRight":{
                            "show":true,
                            "chinese":"附条件判决右"
                        }
                    }
                },
                "women":{
                    "show":true,
                    "chinese":"女",
                    "child":{
                        "conditionalJudgment":{
                            "show":true,
                            "chinese":"附条件判决"
                        },
                        "conditionalJudgmentRight":{
                            "show":true,
                            "chinese":"附条件判决右"
                        }
                    }
                }
            }
        }
    },
    "modules":{
        "data-params-list-SkinImprove-enable":{
            "tree":"data-params-list-SkinImprove-enable",
            "show":true,
            "type":"switch",
            "value":"1",
            "chinese":"是否启用",
            "readyOnly":true
        },
        "data-params-list-HighPass-enable":{
            "tree":"",
            "show":true,
            "type":"switch",
            "value":"1",
            "chinese":"是否启用",
            "readyOnly":false
        },
        "data-params-list-HighPass-useFaceMask-enable":{
            "tree":"",
            "show":true,
            "type":"switch",
            "value":"1",
            "chinese":"是否启用",
            "readyOnly":false
        },
        "data-params-list-HighPass-useFaceMask-blendOpacity":{
            "show":true,
            "type":"input",
            "value":"1",
            "chinese":"混合不透明度",
            "readyOnly":false
        },
        "data-params-list-Makeup-liangYan":{
            "show":true,
            "type":"radioNumber",
            "value":"1",
            "chinese":"亮眼",
            "readyOnly":false
        },
        "data-params-list-Makeup-men-shouBi":{
            "show":true,
            "type":"radioNumber",
            "value":"1",
            "chinese":"男：瘦鼻",
            "readyOnly":false
        },
        "data-params-list-Makeup-men-daYan":{
            "show":true,
            "type":"radioNumber",
            "value":"1",
            "chinese":"男：大眼",
            "readyOnly":false
        }
    }
}

export default treeRule;
